### ISSUE TITLE
NoMethodError: undefined method `keys' for "year":String

### ISSUE THREAD

**Issue by Lordnibbler** [cyclotron3k/flickr#3]
Hi,

I've been using flickraw for some years. Over the last few days I started to see a 100% failure rate when making requests to Flickr's API at the `photos.getInfo` endpoint. 

I first landed here at your updated gem, Flickr, and upgraded from Flickraw 0.9.0 to flickr 2.0.2. However, I still see the same error, even when running [the "Simple" example code](https://github.com/cyclotron3k/flickr#simple)

```ruby
7.0.3@3.1.0 (main)> require 'flickr'
flickr = Flickr.new(ENV['FLICKR_API_KEY'], ENV['FLICKR_SECRET'])
list   = flickr.photos.getRecent
id     = list[0].id
secret = list[0].secret
info   = flickr.photos.getInfo :photo_id => id, :secret => secret
# =>
NoMethodError: undefined method `keys' for "year":String

      elsif h.keys == ['_content']
             ^^^^^
from /Users/ben/Code/railsblog/vendor/bundler/ruby/3.1.0/bundler/gems/flickr-9ced8cdfa592/lib/flickr/response.rb:11:in `build'
```

It seems the response builder logic is receiving a string `"year"` instead of a hash for the `getInfo` method call. The `getRecent` call appears to succeed:

```ruby
7.0.3@3.1.0 (main)> list.count
=> 100
7.0.3@3.1.0 (main)> 
id     = list[0].id
secret = list[0].secret
7.0.3@3.1.0 (main)> id
=> "52082470912"
7.0.3@3.1.0 (main)> secret
=> "6db346ee90"
```

Any idea what is going wrong here?

**Comment by Lordnibbler** [comment]
I actually discovered the underlying issue, but I don't know your library's guts well enough to propose a reasonable fix. The `getInfo` endpoint is now returning a seemingly new field, `info["owner"]["gift"]["eligible_durations"]`. this field has a value of `["year", "month", "week"]`, which the response builder seems unable to process with its [current array handling logic](https://github.com/cyclotron3k/flickr/blob/9ced8cdfa59256559368ee2c08669c80649d60cc/lib/flickr/response.rb#L24)

```
=> {"id"=>"49823443921",
 "secret"=>"1edf677c80",
 "server"=>"65535",
 "farm"=>66,
 "dateuploaded"=>"1587941288",
 "isfavorite"=>0,
 "license"=>"0",
 "safety_level"=>"0",
 "rotation"=>0,
 "owner"=>
  {"nsid"=>"33668819@N03",
   "username"=>"Ben Radler",
   "realname"=>"",
   "location"=>nil,
   "iconserver"=>"2457",
   "iconfarm"=>3,
   "path_alias"=>"buhdoo",
   "gift"=>{"gift_eligible"=>true, "eligible_durations"=>["year", "month", "week"], "new_flow"=>false}},
 "title"=>{"_content"=>"DSC00092 (1)"},
 "description"=>{"_content"=>"Slug Bug"},
 "visibility"=>{"ispublic"=>1, "isfriend"=>0, "isfamily"=>0},
 "dates"=>{"posted"=>"1587941288", "taken"=>"2019-01-29 16:39:15", "takengranularity"=>0, "takenunknown"=>"0", "lastupdate"=>"1587941289"},
 "views"=>"26",
 "editability"=>{"cancomment"=>0, "canaddmeta"=>0},
 "publiceditability"=>{"cancomment"=>0, "canaddmeta"=>0},
 "usage"=>{"candownload"=>0, "canblog"=>0, "canprint"=>0, "canshare"=>1},
 "comments"=>{"_content"=>"0"},
 "notes"=>{"note"=>[]},
 "people"=>{"haspeople"=>0},
 "tags"=>{"tag"=>[]},
 "urls"=>{"url"=>[{"type"=>"photopage", "_content"=>"https://www.flickr.com/photos/buhdoo/49823443921/"}]},
 "media"=>"photo"}
```

I'll work around it for now by forking the library and deleting that new field.

**Comment by cyclotron3k** [comment]
This is very odd. I was able to replicate the issue yesterday, but when I went through the exact same steps today, I could not.

I wonder if Flickr have partially deployed API changes to their fleet of servers :thinking:

**Comment by Lordnibbler** [comment]
Perhaps they rolled back the change, or as you suggested, perhaps it is canaried on a few servers and not fully released.

**Comment by cyclotron3k** [comment]
Actually - it's looking like certain photos are affected, and others are not...
```ruby
flickr = Flickr.new
list   = flickr.photos.getRecent
list.map do |photo|
    flickr.photos.getInfo :photo_id => photo.id, :secret => photo.secret
rescue => e
    e.message
end
```

About 50% have the `undefined method` error

**Comment by Lordnibbler** [comment]
Is the error reproducible on the same photo each time? If not it is more likely a feature-flagged or canaried release.

**Comment by cyclotron3k** [comment]
It seems to be reproducible, but if they are sharding requests based on something like photo id, and only half of the servers are updated, we could still see this behaviour...

**Comment by Lordnibbler** [comment]
Can you grab an example response and use it as a mock in order to craft a solution that works for either response in the response builder logic in the gem?

**Comment by cyclotron3k** [comment]
Yes, I have some samples now. Arrays of strings are not handled well, and apparently this is the first time the API has returned arrays of strings!

Fix incoming...

**Comment by cyclotron3k** [comment]
Pushed v2.1.0 to RubyGems - thanks for you help on this one. Let me know if there are any more issues!

**Comment by Lordnibbler** [comment]
Perfect, working great now! You rock
